# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Update dependencies

on: 
  schedule:
  # At 00:00 UTC every day.
  - cron:  '0 0 * * *'
  
  repository_dispatch:
    types: update-dependencies

  workflow_dispatch:

jobs:
  update-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    secrets: inherit
    with:
      solutionsToCheck: 'CCSWE.nanoFramework.Mediator.sln'
      branchToPr: 'master'